import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';
import type { TrainingSession } from '../data/domain';

function formatDate(iso?: string): string {
  if (!iso) return 'Unknown date';
  return new Date(iso).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' });
}

function sessionHtml(sessions: TrainingSession[], title: string): string {
  const rows = sessions.map((s) => `
    <tr>
      <td>${formatDate(s.completedAt)}</td>
      <td>${s.type}</td>
      <td>${s.title}</td>
      <td>${s.durationMinutes} min</td>
      <td>${s.rpe}/10</td>
      <td>${s.score}</td>
      ${s.loadKg != null ? `<td>${s.loadKg} kg</td>` : '<td>—</td>'}
      <td>${s.note ?? ''}</td>
    </tr>`).join('');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<style>
  body { font-family: Arial, sans-serif; font-size: 11px; color: #1a1a1a; margin: 24px; }
  h1 { font-size: 18px; letter-spacing: 2px; text-transform: uppercase; margin-bottom: 4px; }
  p.sub { color: #666; margin: 0 0 16px; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #04080F; color: #00E5FF; text-align: left; padding: 6px 8px; font-size: 10px; text-transform: uppercase; letter-spacing: 1px; }
  td { padding: 5px 8px; border-bottom: 1px solid #eee; vertical-align: top; }
  tr:nth-child(even) td { background: #f8f8f8; }
  .footer { margin-top: 20px; color: #999; font-size: 9px; }
</style>
</head>
<body>
<h1>// FORGE Tactical Fitness</h1>
<p class="sub">${title} — exported ${formatDate(new Date().toISOString())}</p>
<table>
  <thead>
    <tr>
      <th>Date</th><th>Type</th><th>Session</th><th>Duration</th>
      <th>RPE</th><th>Score</th><th>Load</th><th>Notes</th>
    </tr>
  </thead>
  <tbody>${rows}</tbody>
</table>
<p class="footer">Generated by FORGE Tactical Fitness — ${sessions.length} session${sessions.length !== 1 ? 's' : ''}</p>
</body>
</html>`;
}

export async function exportSessionsToPdf(sessions: TrainingSession[], title = 'Training Log'): Promise<void> {
  if (Platform.OS === 'web') {
    const html = sessionHtml(sessions, title);
    const win = window.open('', '_blank');
    if (win) { win.document.write(html); win.document.close(); win.print(); }
    return;
  }

  const { uri } = await Print.printToFileAsync({ html: sessionHtml(sessions, title) });
  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', UTI: 'com.adobe.pdf' });
  } else {
    await Print.printAsync({ uri });
  }
}
